"""add important indexes

Revision ID: 1642d87bf4e7
Revises: 25939382c298
Create Date: 2025-03-10 11:58:00.388542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1642d87bf4e7"
down_revision: Union[str, None] = "25939382c298"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.create_index(
            op.f("ix_receipt_product_created_at"),
            "receipt_product",
            ["created_at"],
            unique=False,
            postgresql_concurrently=True,
        )
        op.create_index(
            op.f("ix_receipts_created_at"),
            "receipts",
            ["created_at"],
            unique=False,
            postgresql_concurrently=True,
        )
        op.create_index(
            op.f("ix_receipts_payment_type"),
            "receipts",
            ["payment_type"],
            unique=False,
            postgresql_concurrently=True,
        )
        op.create_index(
            op.f("ix_receipts_total"),
            "receipts",
            ["total"],
            unique=False,
            postgresql_concurrently=True,
        )
        op.create_index(
            op.f("ix_users_created_at"),
            "users",
            ["created_at"],
            unique=False,
            postgresql_concurrently=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_receipts_total"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_payment_type"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_created_at"), table_name="receipts")
    op.drop_index(op.f("ix_receipt_product_created_at"), table_name="receipt_product")
    # ### end Alembic commands ###
